### PR TITLE
Fix insert button position

### PR DESCRIPTION
**Pull request by thegeorgeous**
Insert button is better placed in the next row. Being in the same row messes up the text in medium-sized screens
#### New position

chalimachine 2016-07-09 12-18-36

### CODE REVIEW

**Comment by lebmatter** [comment]
Which browser has this issue?

**Comment by shahimclt** [comment]
I think OP @thegeorgeous means lower res displays, (e.g old CRTs with 1024*768) and maybe some tablets I guess.

ss2

This fix will make the site look good on smaller screens for the time being, until a responsive overhaul is made.

**Comment by hfactor** [comment]
@zmattra I can replicate the issue in my mac too. The right side bar is a bit thinner. And this is a #quickfix I recommend this 👍

**Comment by lebmatter** [comment]
This will take the button to the next row. Is it ok for UI? @hfactor also see the gap it creates after size selector.

**Comment by shahimclt** [comment]
@thegeorgeous @zmattra maybe you could try expanding the font combo box to fill the gap.

**Comment by lebmatter** [comment]
That font combo box must be the problem. Its not responsive.

**Comment by thegeorgeous** [comment]
@zmattra, @shahimclt, This is just a temporary fix. Proper UI/UX changes need to be done anyway

**Comment by lebmatter** [comment]
Yes.

**Pull request merged**
