### PR TITLE
Fix vertical scroll bug

### LINKED ISSUE #25: Avoid vertical scrolling
The webpage does not need scrollbars. Avoid scrolling and place the tools as fixed. The canvas, if user decide to expand, can be optionally scrollable

### PR DESCRIPTION
**Pull request by thegeorgeous**
Fixes #25

### CODE REVIEW

**Comment by stultus** [comment]
@thegeorgeous can you rebase this pr to fix the conflicts ?

**Comment by lebmatter** [comment]
This is breaking the layout.
overflowbug

**Comment by hfactor** [comment]
Working fine for me. In firefox.

**Comment by lebmatter** [comment]
Working on a UI redesign. This will be fixed in next version.

**Pull request closed without merging**
