### PR TITLE
Deselect layers when textarea gets focus

### PR DESCRIPTION
**Pull request by shahimclt**
Fixes issues #41  and #42 .

### CODE REVIEW

**Comment by stultus** [comment]
Thanks :+1:

**Comment by shahimclt** [comment]
ur welcome. but did you test that? coz I'm mind-compiling here. Don't have a test env.

**Comment by stultus** [comment]
yep.  working smoothly

**Comment by stultus** [comment]
This is the steps to follow to make it running in local 

in the project directory 
`mkdir env`
`virtualenv env`    (install python-virtualenv if not installed) 
`source env/bin/activate`
`pip install -r requirements.txt`
`python manage.py migrate`
`python manage.py createsuperuser`   (set  a username and password) 
`python manage.py runserver`  ( now the should run smoothly) 

Now head to http://localhost:8000/admin 
Create a comic collection object. and then add some comic image objects (and assign the collection) 

after this 
http://localhost:8000 should give you a live local instant with some test images

**Pull request merged**
