### PR TITLE
Added Cntrl+M key shortcut for switching language.

### LINKED ISSUE #34: [Feature Req] Keyboard Shortcut to switch language while typing.
ഇതുപോലെ English ഉം മലയാളയവും Mix ചെയ്തു type ചെയ്യാന്‍ വളരെ ബുദ്ധിമുട്ടാണു. 
It would be convenient to have a keyboard shortcut to swap language while typing.

### PR DESCRIPTION
**Pull request by shahimclt**
fixes #34 [I hope].

chalistrip

Guys, I am not familiar with Django, So I haven't been able to figure out how to set up a test env.
Please test this out for me and let me know of any issues. thanks.

### CODE REVIEW

**Comment by stultus** [comment]
can we have cntrl + m  for switching the langauge?   That is the usual combinations used everywhere (wikipedia for eg)

**Comment by shahimclt** [comment]
@stultus can you test if this one works without issues? I'll change the key combo.

**Comment by shahimclt** [comment]
Ctrl+M is assigned to "Mute tab" in some browsers is it good to override that?

**Comment by stultus** [comment]
It should be fine to override the mute tab feature, because there is nothing to mute in our tab :) 
And yeah I will test it and let you know. Now at work

**Comment by stultus** [comment]
Merging , Thanks !! :+1:

**Pull request merged**
