### PR TITLE
Add delete button functionality

### LINKED ISSUE #2: [Feature Request] Add Keyboard Shortcut for Delete
കീബോർഡിലെ ഡിലീറ്റ്  ബട്ടൺ ഞെക്കിയാൽ തിരഞ്ഞെടുത്തിരിക്കണ വസ്തു ഡിലീറ്റായാൽ നന്നായിരുന്നു.

### PR DESCRIPTION
**Pull request by thegeorgeous**
Fixes #2

### CODE REVIEW

**Comment by shahimclt** [comment]
പുള്ള് മുതലാളീ. @thegeorgeous 
keycode 8 is "Backspace/delete"
u should also include keycode 46 for the delete key.

see [here](http://keycode.info/)

**Comment by shahimclt** [comment]
http://keycode.info/

**Comment by thegeorgeous** [comment]
@shahimclt, using mac, delete and backspace are all the same for me :-D. Have added it. Can you test on Windows/Linux if it works?

**Comment by stultus** [comment]
Perfect.  Tested and is working fine. merging

**Pull request merged**
