### PR TITLE
Enabled multiple object selection and text element resize

### PR DESCRIPTION
**Pull request by eternalthinker**
- Enabled multiple object selection (mouse drag, shift-click)
- Enabled resize of newly added text content (Fixed in this change set as it prevents group selection from scale transform)

Changed behaviour on text scaling: 
With Textbox, horizontal scaling would rearrange wrapping of text. Now the text skews on horizontal-only scaling, but nevertheless gives control to adjust font size after adding to canvas.

### CODE REVIEW

**Comment by stultus** [comment]
These changes breaks text wrapping !

**Comment by eternalthinker** [comment]
@stultus 
Yes, mentioned it in change description; It is a choice of font resizing vs wrapping.
Also scaling in multi-selection doesn't work when textbox is included

**Comment by stultus** [comment]
text wrapping is a must.  I think the resizing limitations are of the library used. 

@zmattra inputs please :)

**Comment by lebmatter** [comment]
We were using IText. But because of lack of text wrap support, changed to Textbox. 

But I have seen a textalign option in itext too. 
See http://fabricjs.com/docs/fabric.IText.html
I could never make it work.
But it is working in their demo
See: http://fabricjs.com/test/misc/itext.html

Since we could not implement IText textalign, we used Textbox.

**Comment by eternalthinker** [comment]
@zmattra Okay. But does alignment alone validate use of IText? I believe the issue here is with wrapping support?

**Comment by eternalthinker** [comment]
Enabled scaling of Textbox in a group selection with an extended class ScalableTextbox.
The wrapping behaves exactly like Textbox when working with the individual element, and text scaling in group transform behaves exactly like IText (also implies text can be skewed like IText during x-only or y-only scaling)

**Comment by stultus** [comment]
Works perfectly.  
Merging..  :+1:   Thanks :)

**Pull request merged**
